// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPpH8x8kREUpAwJxV3XYyDTEXzMJqv1LY',
    appId: '1:321687917971:web:fd026ce6de333648148466',
    messagingSenderId: '321687917971',
    projectId: 'flui-app-1cd4e',
    authDomain: 'flui-app-1cd4e.firebaseapp.com',
    storageBucket: 'flui-app-1cd4e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZGaTjg2UGOOVvVUmC477B47Mp2NSYHzg',
    appId: '1:321687917971:android:c74d3cb4dd23b99f148466',
    messagingSenderId: '321687917971',
    projectId: 'flui-app-1cd4e',
    storageBucket: 'flui-app-1cd4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0LbGgskeOFimKFOhUyjxz0j0wiMMx3E8',
    appId: '1:321687917971:ios:aa212548568c5354148466',
    messagingSenderId: '321687917971',
    projectId: 'flui-app-1cd4e',
    storageBucket: 'flui-app-1cd4e.firebasestorage.app',
    iosBundleId: 'com.example.fluiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0LbGgskeOFimKFOhUyjxz0j0wiMMx3E8',
    appId: '1:321687917971:ios:aa212548568c5354148466',
    messagingSenderId: '321687917971',
    projectId: 'flui-app-1cd4e',
    storageBucket: 'flui-app-1cd4e.firebasestorage.app',
    iosBundleId: 'com.example.fluiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPpH8x8kREUpAwJxV3XYyDTEXzMJqv1LY',
    appId: '1:321687917971:web:2f6700f6788355d8148466',
    messagingSenderId: '321687917971',
    projectId: 'flui-app-1cd4e',
    authDomain: 'flui-app-1cd4e.firebaseapp.com',
    storageBucket: 'flui-app-1cd4e.firebasestorage.app',
  );
}
